### ISSUE TITLE
clarification of `ATMMetaForce` global parameters

### ISSUE THREAD

**Issue by dominicrufa** [Gallicchio-Lab/openmm-atmmetaforce-plugin#1]
hi, I am digging into the ATM methodology and the implementation via the plugin. I am looking at the example in the `readme`:
```
u0 = 0.0 * kilocalorie_per_mole
w0coeff = 0.0 * kilocalorie_per_mole
umsc =  200.0 * kilocalorie_per_mole
ubcore = 100.0 * kilocalorie_per_mole
```
but I am confused as to what term `ubcore` corresponds to in eq 4 in the absolute [ATM paper](https://pubs.acs.org/doi/pdf/10.1021/acs.jctc.1c00266).

**Comment by egallicc** [comment]
Thank you for your interest. `ubcore` refers to `u_0` in eq. 4. It sets the lower limit at which the soft-core perturbation energy function is active. `umsc` in the script refers to `u_max` in eq. 4.

There is an unfortunate inconsistency in the paper. Eqs. 3 and 4 both refer to terms called `u0` which refer to different quantities. In eq. 3 `u0` is a function of `lambda` and controls the position of the transition from one linear branch of the softplus function to the other. The meaning of `u0` in eq. 4 has to do with the soft-core perturbation energy as discussed above.

**Comment by dominicrufa** [comment]
it looks like from [SoftCoreF](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin/blob/eb327b1b479ba52ae30ca8b6fee7b118b43244d5/platforms/common/src/CommonATMMetaForceKernels.cpp#L19-L30), `ubcore` defines the lower energy _inside_ the softcore fn, but `u0` is used in the _softplus_.

I think there is just a difference in the definition of the alchemical fns in the absolute and relative papers. In the rbfe paper, the softcore fn in eq 11 uses `u_c`, not reusing "u_0" (as in the abfe paper). I.e. the rbfe paper, has 1 more term than the abfe paper, hence the additional term. correct me if this is wrong.

**Comment by dominicrufa** [comment]
^sorry, did not see your response @egallicc. let me give this a read and see if i understand.

**Comment by dominicrufa** [comment]
@egallicc , I see:

> The meaning of u0 in eq. 4 has to do with the soft-core perturbation energy as discussed above.

`u0` only seems to appear as an offset in the softplus exponential [here](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin/blob/eb327b1b479ba52ae30ca8b6fee7b118b43244d5/platforms/common/src/CommonATMMetaForceKernels.cpp#L188). thank you for the clarification.

**Comment by egallicc** [comment]
Correct. `u_0` in eq. 3 of the Wu et al. (2021) paper corresponds to `u0` in the code. `u_0` in eq. 4 of the same paper corresponds to `ubcore` in the code.

The Azimi et al. (2022) paper corrects the formal inconsistency. There `ubcore` in the code corresponds to `u_c` of eq. 11.
