### ISSUE TITLE
Examples & Docmentation to run this for RBFE calculation from docked structures

### ISSUE THREAD

**Issue by JSLJ23** [Gallicchio-Lab/openmm-atmmetaforce-plugin#2]
Hi developers of openmm-atm,

I was wondering if there was any available documentation / example code of how to run a RBFE for docked ligands against a PDB with a known co-cystal structure and ground truth affinity value.
I have some structures of ligand SDF files that were docked against a protein with a known hit and Kd/i values and I was hoping to run this to get predictions of binding energies of those docked ligands with respect to a known ground truth.

Thank you.

**Comment by egallicc** [comment]
Use the [AToM-OpenMM](https://github.com/Gallicchio-Lab/AToM-OpenMM) middleware. The [CDK2](https://github.com/Gallicchio-Lab/AToM-OpenMM/tree/master/examples/RBFE/cdk2) example is probably a good starting point for your purpose.

**Comment by JSLJ23** [comment]
Ahh ok thank you, I'll look at the ABFE examples there :)
