### ISSUE TITLE
`ATMMetaForce` objects are not serializeable

### ISSUE THREAD

**Issue by SimonBoothroyd** [Gallicchio-Lab/openmm-atmmetaforce-plugin#4]
The `ATMMetaForce` object does not register a serialization proxy, and so instances of it and any systems containing such a force are not serializable using the OpenMM `openmm.XmlSerializer.serialize` interface.

Trying to serialize just the force, for example,

```
import atmmetaforce
import openmm

force = atmmetaforce.ATMMetaForce(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, [])
openmm.XmlSerializer.serialize(force)
```

will produce the following error:

```
object = <atmmetaforce.ATMMetaForce; proxy of <Swig Object of type 'ATMMetaForcePlugin::ATMMetaForce *' at 0x16fd27360> >

    @staticmethod
    def _serializeForce(object):
        r"""_serializeForce(object) -> std::string"""
>       return _openmm.XmlSerializer__serializeForce(object)
E       openmm.OpenMMException: There is no serialization proxy registered for type N18ATMMetaForcePlugin12ATMMetaForceE
```

**Comment by egallicc** [comment]
Thank you for pointing this out. What would be the process to enable serialization? And which use cases would it apply to? 

The ATM Meta Force is not a standard Force. It manages a set of Forces.

**Comment by peastman** [comment]
Serialization is pretty easy.  You just write and register a serialization proxy class that knows how to save and load objects of your class.  The example plugin [includes code for this](https://github.com/openmm/openmmexampleplugin/tree/master/serialization).

Although ATMMetaForce manages other forces, it just does it through force groups, so it doesn't need to concern itself with the details of the forces it works with.  Basically you just need to save the internal state of the ATMMetaForce:

https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin/blob/cbd7a62fefee4ff07ee90248af8600ab211c8f3e/openmmapi/include/ATMMetaForce.h#L303-L313

If you save and restore all those fields, that should be enough to accurately reconstruct the object.  You can find lots of examples of serialization proxies in https://github.com/openmm/openmm/tree/master/serialization/src.

**Comment by SimonBoothroyd** [comment]
> And which use cases would it apply to?

In this case I was trying to save the system out to XML while debugging a few issues with a simulation. It can also be useful to save the system to disk between different parts of a workflow depending on how it is being executed!

> What would be the process to enable serialization?

@peastman beat me to it! @egallicc would you accept a PR adding serialisation?

**Comment by egallicc** [comment]
Thank you all for the excellent explanations.

Accept a PR? We would love to have a PR!

Let me know if we can help in any way. Note that, similarly to the CustomCVForce, the ATM Meta Force duplicates the Forces it manages into "inner" Contexts. I guess each one will need to be serialized and deserialized into the appropriate inner Context? 

We don't change the Forces in any way. We simply duplicate them. The inner Contexts differ only on the system coordinates they are given.

**Comment by SimonBoothroyd** [comment]
Fantastic! The PR should be up.

> Note that, similarly to the CustomCVForce, the ATM Meta Force duplicates the Forces it manages into "inner" Contexts. I guess each one will need to be serialized and deserialized into the appropriate inner Context?

From @peastman's comment above it sounds like we should be safe to just serialize the properties of the ATM force without serializing any of the managed forces, but I'm for sure not too familiar with how OpenMM handles serialization so Peter would probably need to answer this!

**Comment by peastman** [comment]
> Note that, similarly to the CustomCVForce, the ATM Meta Force duplicates the Forces it manages into "inner" Contexts.

I assume that happens at Context creation?  It isn't like CustomCVForce, which directly stores a list of Force objects.  As long as you accurately recreate the ATMMetaForce object, everything should work correctly when you create a new Context.  Is that correct?

**Comment by egallicc** [comment]
Yes, ATMMetaForce duplicates the Forces in each group it is given when the Context is created. So, yes, it would work if the deserialization included creating ATMMetaForce with the system forces in place and appropriately assigned to groups.

But then it would be like doing the initialization almost from scratch. Isn't serialization/deserialization supposed to shortcut some of these things?

**Comment by peastman** [comment]
It happens inside ATMMetaForceImpl, which is part of the Context.  Serialization saves the System, not the Context.  After loading the serialized System, you create a new Context for it.

> Isn't serialization/deserialization supposed to shortcut some of these things?

It isn't meant to speed up Context creation.  It's just supposed to faithfully recreate the serialized objects (usually a System or Integrator).

**Comment by egallicc** [comment]
Thank you for the clarification.

**Comment by SimonBoothroyd** [comment]
Amazing thank you both for the great discussion and getting this in! @egallicc would you be open to creating a new release that contains this addition?

**Comment by egallicc** [comment]
Yes, I will try. I was told that a new release could be automagically picked up by the conda-forge feedstock. I am trying to confirm before pulling the trigger.

**Comment by egallicc** [comment]
@SimonBoothroyd could you please address @peastman [comment](https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin/pull/5#discussion_r1154741459).

**Comment by SimonBoothroyd** [comment]
Absolutely - I've opened #6 to update the names

**Comment by egallicc** [comment]
Thanks!

**Comment by SimonBoothroyd** [comment]
@peastman I'm still running into a couple of odd issues with the serialization code that would be great to get your advice on!

When serializing on OSX from python the serialize and deserialize functions appear to execute fine, however the object returned by:

```
import atmmetaforce
import openmm

force = atmmetaforce.ATMMetaForce(
    0.0, 0.0, 0.0, 0.0, 0.0, 800.0, 400.0, 1.0 / 16.0, 1.0, [3]
)
force = openmm.XmlSerializer.deserialize(openmm.XmlSerializer.serialize(force))
print(type(force), flush=True)
```
is `<class 'openmm.openmm.Force'>` rather than `<class 'atmmetaforce.ATMMetaForce'>` as expected. 

If I run `auto* copy = XmlSerializer::deserialize<Force>(buffer);` from C++ however then `copy` is type `ATMMetaForce` as expected. Should I have added something to the serialization code to handle casting?

The second issue is that on Linux I'm still seeing the `There is no serialization proxy registered for type N18ATMMetaForcePlugin12ATMMetaForceE`, which I'm guessing is caused by the `void __attribute__((constructor))` not being called when the shared plugin library is loaded as expected.

I guess this is related to [these](https://www.reddit.com/r/cpp_questions/comments/10oyuzi/attribute_constructor_shared_library_not_getting/), [kinds](https://stackoverflow.com/questions/48212805/why-is-attribute-constructor-in-my-shared-library-not-working) of issues, but this is my first time using this loading mechanism so I'm not 100% sure how to resolve this cleanly. Do you have any advice? Is there a change needed in this plugin or is this a fix that would be needed in OpenMM?

**Comment by peastman** [comment]
This is a limitation of how SWIG works.  If a function is declared to return a parent class like Force, and you want it to actually return an instance of the correct Python subclass, you need to give it a list of every possible subclass at build time.  We can do that for all the built in subclasses, but not ones defined in external plugins.  The workaround is to provide `cast()` and `isinstance()` methods so you can cast it by hand.  See https://github.com/openmm/openmmexampleplugin/blob/6340817d2c53105c0cb8c862d83653b7ebc079db/python/exampleplugin.i#L85-L93.

I don't know why it wouldn't work on Linux.  You mark the registration function as a constructor:

https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin/blob/459e07a6f6788992d1d3d7450e227accf3f5bfb9/serialization/src/SerializationProxyRegistration.cpp#L15

That ought to make it get called when the library is loaded.  It's the same thing we do in other plugins, and they work on Linux.  Can you check whether that function is getting called?

Possibly your plugin isn't getting loaded at all?  You can check `openmm.pluginLoadedLibNames` for a list of all plugins that were loaded, and `Platform.getPluginLoadFailures()` for errors that prevented plugins from being loaded.
